//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.01 at 11:51:00 AM PST 
//


package com.expd.xsd.cdb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AppType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CCXORDER"/&gt;
 *     &lt;enumeration value="CDBEXPORT"/&gt;
 *     &lt;enumeration value="CDBIMPORT"/&gt;
 *     &lt;enumeration value="ORDERS"/&gt;
 *     &lt;enumeration value="VDFTest1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AppType")
@XmlEnum
public enum AppType {

    CCXORDER("CCXORDER"),
    CDBEXPORT("CDBEXPORT"),
    CDBIMPORT("CDBIMPORT"),
    ORDERS("ORDERS"),
    @XmlEnumValue("VDFTest1")
    VDF_TEST_1("VDFTest1");
    private final String value;

    AppType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AppType fromValue(String v) {
        for (AppType c: AppType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
