//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 04:02:39 PM PST 
//


package com.expd.xsd.cdb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 *  routing rules section for a CDB application queue (e.g., CDBIMPORT,
 * 				CDBEXPORT, CCXORDER) 
 * 
 * <p>Java class for CDBApplicationQueueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CDBApplicationQueueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="default-routing-rule" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="failed-routing-rule" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="system-destin-default" type="{http://www.expd.com/xsd/cdb}DefaultSystemDestin" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="cdb-routing-rule" type="{http://www.expd.com/xsd/cdb}CDBRoutingRuleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="copy-routing-rule" type="{http://www.expd.com/xsd/cdb}CopyRoutingRuleType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.expd.com/xsd/cdb}AppType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDBApplicationQueueType", propOrder = {
    "defaultRoutingRule",
    "failedRoutingRule",
    "systemDestinDefault",
    "cdbRoutingRule",
    "copyRoutingRule"
})
public class CDBApplicationQueueType
    implements ToString
{

    @XmlElement(name = "default-routing-rule", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String defaultRoutingRule;
    @XmlElement(name = "failed-routing-rule", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String failedRoutingRule;
    @XmlElement(name = "system-destin-default")
    protected List<DefaultSystemDestin> systemDestinDefault;
    @XmlElement(name = "cdb-routing-rule")
    protected List<CDBRoutingRuleType> cdbRoutingRule;
    @XmlElement(name = "copy-routing-rule")
    protected List<CopyRoutingRuleType> copyRoutingRule;
    @XmlAttribute(name = "name", required = true)
    protected AppType name;

    /**
     * Gets the value of the defaultRoutingRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultRoutingRule() {
        return defaultRoutingRule;
    }

    /**
     * Sets the value of the defaultRoutingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultRoutingRule(String value) {
        this.defaultRoutingRule = value;
    }

    /**
     * Gets the value of the failedRoutingRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailedRoutingRule() {
        return failedRoutingRule;
    }

    /**
     * Sets the value of the failedRoutingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailedRoutingRule(String value) {
        this.failedRoutingRule = value;
    }

    /**
     * Gets the value of the systemDestinDefault property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemDestinDefault property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemDestinDefault().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefaultSystemDestin }
     * 
     * 
     */
    public List<DefaultSystemDestin> getSystemDestinDefault() {
        if (systemDestinDefault == null) {
            systemDestinDefault = new ArrayList<DefaultSystemDestin>();
        }
        return this.systemDestinDefault;
    }

    /**
     * Gets the value of the cdbRoutingRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdbRoutingRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCdbRoutingRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDBRoutingRuleType }
     * 
     * 
     */
    public List<CDBRoutingRuleType> getCdbRoutingRule() {
        if (cdbRoutingRule == null) {
            cdbRoutingRule = new ArrayList<CDBRoutingRuleType>();
        }
        return this.cdbRoutingRule;
    }

    /**
     * Gets the value of the copyRoutingRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyRoutingRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyRoutingRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CopyRoutingRuleType }
     * 
     * 
     */
    public List<CopyRoutingRuleType> getCopyRoutingRule() {
        if (copyRoutingRule == null) {
            copyRoutingRule = new ArrayList<CopyRoutingRuleType>();
        }
        return this.copyRoutingRule;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link AppType }
     *     
     */
    public AppType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppType }
     *     
     */
    public void setName(AppType value) {
        this.name = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theDefaultRoutingRule;
            theDefaultRoutingRule = this.getDefaultRoutingRule();
            strategy.appendField(locator, this, "defaultRoutingRule", buffer, theDefaultRoutingRule);
        }
        {
            String theFailedRoutingRule;
            theFailedRoutingRule = this.getFailedRoutingRule();
            strategy.appendField(locator, this, "failedRoutingRule", buffer, theFailedRoutingRule);
        }
        {
            List<DefaultSystemDestin> theSystemDestinDefault;
            theSystemDestinDefault = (((this.systemDestinDefault!= null)&&(!this.systemDestinDefault.isEmpty()))?this.getSystemDestinDefault():null);
            strategy.appendField(locator, this, "systemDestinDefault", buffer, theSystemDestinDefault);
        }
        {
            List<CDBRoutingRuleType> theCdbRoutingRule;
            theCdbRoutingRule = (((this.cdbRoutingRule!= null)&&(!this.cdbRoutingRule.isEmpty()))?this.getCdbRoutingRule():null);
            strategy.appendField(locator, this, "cdbRoutingRule", buffer, theCdbRoutingRule);
        }
        {
            List<CopyRoutingRuleType> theCopyRoutingRule;
            theCopyRoutingRule = (((this.copyRoutingRule!= null)&&(!this.copyRoutingRule.isEmpty()))?this.getCopyRoutingRule():null);
            strategy.appendField(locator, this, "copyRoutingRule", buffer, theCopyRoutingRule);
        }
        {
            AppType theName;
            theName = this.getName();
            strategy.appendField(locator, this, "name", buffer, theName);
        }
        return buffer;
    }

}
