//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 04:02:39 PM PST 
//


package com.expd.xsd.cdb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DomainType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INT"/&gt;
 *     &lt;enumeration value="DEV"/&gt;
 *     &lt;enumeration value="QA"/&gt;
 *     &lt;enumeration value="PROD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DomainType")
@XmlEnum
public enum DomainType {

    INT,
    DEV,
    QA,
    PROD;

    public String value() {
        return name();
    }

    public static DomainType fromValue(String v) {
        return valueOf(v);
    }

}
