//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 03:55:34 PM PST 
//


package com.expd.xsd.cdb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 *  Contains routing rules for an application domain (e.g., dev, qa,
 * 				prod) 
 * 
 * <p>Java class for EnvironmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvironmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cdb-application-queue" type="{http://www.expd.com/xsd/cdb}CDBApplicationQueueType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="domain" use="required" type="{http://www.expd.com/xsd/cdb}DomainType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvironmentType", propOrder = {
    "cdbApplicationQueue"
})
public class EnvironmentType
    implements ToString
{

    @XmlElement(name = "cdb-application-queue", required = true)
    protected List<CDBApplicationQueueType> cdbApplicationQueue;
    @XmlAttribute(name = "domain", required = true)
    protected DomainType domain;

    /**
     * Gets the value of the cdbApplicationQueue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdbApplicationQueue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCdbApplicationQueue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDBApplicationQueueType }
     * 
     * 
     */
    public List<CDBApplicationQueueType> getCdbApplicationQueue() {
        if (cdbApplicationQueue == null) {
            cdbApplicationQueue = new ArrayList<CDBApplicationQueueType>();
        }
        return this.cdbApplicationQueue;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link DomainType }
     *     
     */
    public DomainType getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainType }
     *     
     */
    public void setDomain(DomainType value) {
        this.domain = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<CDBApplicationQueueType> theCdbApplicationQueue;
            theCdbApplicationQueue = (((this.cdbApplicationQueue!= null)&&(!this.cdbApplicationQueue.isEmpty()))?this.getCdbApplicationQueue():null);
            strategy.appendField(locator, this, "cdbApplicationQueue", buffer, theCdbApplicationQueue);
        }
        {
            DomainType theDomain;
            theDomain = this.getDomain();
            strategy.appendField(locator, this, "domain", buffer, theDomain);
        }
        return buffer;
    }

}
