//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 03:55:34 PM PST 
//


package com.expd.xsd.cdb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.expd.xsd.cdb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RoutingRules_QNAME = new QName("http://www.expd.com/xsd/cdb", "routing-rules");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.expd.xsd.cdb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoutingRulesType }
     * 
     */
    public RoutingRulesType createRoutingRulesType() {
        return new RoutingRulesType();
    }

    /**
     * Create an instance of {@link CDBRoutingRuleType }
     * 
     */
    public CDBRoutingRuleType createCDBRoutingRuleType() {
        return new CDBRoutingRuleType();
    }

    /**
     * Create an instance of {@link CopyRoutingRuleType }
     * 
     */
    public CopyRoutingRuleType createCopyRoutingRuleType() {
        return new CopyRoutingRuleType();
    }

    /**
     * Create an instance of {@link DefaultSystemDestin }
     * 
     */
    public DefaultSystemDestin createDefaultSystemDestin() {
        return new DefaultSystemDestin();
    }

    /**
     * Create an instance of {@link CDBApplicationQueueType }
     * 
     */
    public CDBApplicationQueueType createCDBApplicationQueueType() {
        return new CDBApplicationQueueType();
    }

    /**
     * Create an instance of {@link EnvironmentType }
     * 
     */
    public EnvironmentType createEnvironmentType() {
        return new EnvironmentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoutingRulesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.expd.com/xsd/cdb", name = "routing-rules")
    public JAXBElement<RoutingRulesType> createRoutingRules(RoutingRulesType value) {
        return new JAXBElement<RoutingRulesType>(_RoutingRules_QNAME, RoutingRulesType.class, null, value);
    }

}
