//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.14 at 09:09:11 AM PDT 
//


package com.expd.xsd.jms.cdb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JMSDomainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JMSDomainType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INT"/>
 *     &lt;enumeration value="DEV"/>
 *     &lt;enumeration value="QA"/>
 *     &lt;enumeration value="PROD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JMSDomainType")
@XmlEnum
public enum JMSDomainType {

    INT,
    DEV,
    QA,
    PROD;

    public String value() {
        return name();
    }

    public static JMSDomainType fromValue(String v) {
        return valueOf(v);
    }

}
