//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.14 at 09:09:11 AM PDT 
//


package com.expd.xsd.jms.cdb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JMSEnvironmentType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="JMSEnvironmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jms-provider" type="{http://www.expd.com/xsd/jms/cdb}JMSProviderType"/>
 *         &lt;element name="backup-jms-provider" type="{http://www.expd.com/xsd/jms/cdb}JMSProviderType" minOccurs="0"/>
 *         &lt;element name="email-contact" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".+\@.+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="domain" use="required" type="{http://www.expd.com/xsd/jms/cdb}JMSDomainType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JMSEnvironmentType", propOrder = {
        "jmsProvider",
        "backupJmsProvider",
        "emailContact"
})
public class JMSEnvironmentType {

    @XmlElement(name = "jms-provider", required = true)
    protected JMSProviderType jmsProvider;
    @XmlElement(name = "backup-jms-provider")
    protected JMSProviderType backupJmsProvider;
    @XmlElement(name = "email-contact", required = true)
    protected List<String> emailContact;
    @XmlAttribute(required = true)
    protected JMSDomainType domain;

    /**
     * Gets the value of the jmsProvider property.
     *
     * @return possible object is
     * {@link JMSProviderType }
     */
    public JMSProviderType getJmsProvider() {
        return jmsProvider;
    }

    /**
     * Sets the value of the jmsProvider property.
     *
     * @param value allowed object is
     *              {@link JMSProviderType }
     */
    public void setJmsProvider(JMSProviderType value) {
        this.jmsProvider = value;
    }

    /**
     * Gets the value of the backupJmsProvider property.
     *
     * @return possible object is
     * {@link JMSProviderType }
     */
    public JMSProviderType getBackupJmsProvider() {
        return backupJmsProvider;
    }

    /**
     * Sets the value of the backupJmsProvider property.
     *
     * @param value allowed object is
     *              {@link JMSProviderType }
     */
    public void setBackupJmsProvider(JMSProviderType value) {
        this.backupJmsProvider = value;
    }

    /**
     * Gets the value of the emailContact property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailContact property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailContact().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getEmailContact() {
        if (emailContact == null) {
            emailContact = new ArrayList<String>();
        }
        return this.emailContact;
    }

    /**
     * Gets the value of the domain property.
     *
     * @return possible object is
     * {@link JMSDomainType }
     */
    public JMSDomainType getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     *
     * @param value allowed object is
     *              {@link JMSDomainType }
     */
    public void setDomain(JMSDomainType value) {
        this.domain = value;
    }

}
