//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.14 at 09:09:11 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.expd.com/xsd/jms/cdb", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.expd.xsd.jms.cdb;
